server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eciplanner_auth
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
